import asyncio
from incident_iq.transport_agent.agents.ticketing_coordinator import handle_incident


async def main():

    # -------- SAMPLE INCIDENT INPUTS --------
    incident = {
        "payload_id": "INC-123",
        "message": "Checkout failures spiking",
        "service": "payments-api"
    }

    classifier_payload = {
        "severity_id": 1,
        "matched_pattern": "payment_errors_spike",
        "customer_facing": True,
        "revenue_impacting": True,
        "payload": {
            "error_rate": "18%",
            "region": "us-east-1"
        }
    }

    env_context = "OFF-HOURS (2AM), CUSTOMER-FACING, REVENUE-IMPACTING"

    # -------- RUN FULL PIPELINE --------
    result = await handle_incident(
        incident=incident,
        classifier_payload=classifier_payload,
        env_context=env_context
    )

    print("\n===== PLAN GENERATED BY AGENTS =====")
    print(result["plan"])

    print("\n===== EXECUTION OUTPUT =====")
    print(result["execution"])


if __name__ == "__main__":
    asyncio.run(main())
